### ISSUE TITLE
Sleep issues

### ISSUE THREAD

**Issue by sickypedia** [cmd2001/m710q-ql3x-opencore#1]
Hello, thanks for sharing this. In the repo you mentioned 'Hibernation' is broken. Do you mean sleep? I'm unable to wake device up after using the sleep option.

**Comment by cmd2001** [comment]
The device would wake up instantly after turned to hibernation.

Since the hibernation of macOS depends on Intel ME when using Core Graphics card, which prevents system from booting when using modified laptop GPU, there is no solution.
